//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JquerryAjax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        public int EmployeeID { get; set; }
        [Required(ErrorMessage ="This Field Is Required.")]
        public string Name { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
        public Nullable<int> Salary { get; set; }

        [DisplayName("Image")]
        public string ImagePath { get; set; }



        //isko bind krna hoga agey input field se taka ispe submit ho saka 
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
      
        
        
        //ye default path ha 
        public Employee()
        {
            ImagePath = "~/AppFiles/Images/dp.png";
               
        }




    }
}
